### ISSUE TITLE
Broken SVG asset URLs

### ISSUE THREAD

**Issue by tyzbit** [broglep/homeassistant-meshtastic#88]
### Meshtastic Firmware Version

v2.6.11.60ec05e

## System Information

version | core-2025.7.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
container_arch | amd64
user | root
virtualenv | false
python_version | 3.13.3
os_name | Linux
os_version | 6.1.0-32-amd64
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4998
Installed Version | 2.0.5
Stage | running
Available Repositories | 2122
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 5
views | 18
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), enp3s0 (enabled, default, auto), tunl0 (disabled), calib4abf8dfb89 (disabled), cali4e5185ddf72 (disabled), cali075bff664ca (disabled), cali303eb7967f9 (disabled), cali611775e31e0 (disabled), calib9defee9036 (disabled), calif3ddd7cfa65 (disabled), cali739a2c3981e (disabled), cali86a1a368924 (disabled), cali949064e1ec0 (disabled), cali943fe1d536d (disabled), calicebae852fcf (disabled), caliece5562bcb8 (disabled), calidd74028fb16 (disabled), calia4f62b51bd9 (disabled), cali7e256393c2b (disabled), cali012508cba3f (disabled), calieec56e34117 (disabled), cali09c8effd4ef (disabled), caliabeed7346f8 (disabled), cali7d80f4c964d (disabled), calie0f6baf9f44 (disabled), calibbd7aa3248a (disabled), cali3eb1c02976f (disabled), calid264146f5c7 (disabled), caliea03d497ca9 (disabled), calia828d864d01 (disabled), cali41ae05f0d9c (disabled), cali10d318aef30 (disabled), cali1969a9deee6 (disabled), calidd817121ae6 (disabled), calie7974e17075 (disabled), cali37ea9a823cf (disabled), cali913315f6666 (disabled), calid5f2082038a (disabled), cali20dbd8049a5 (disabled), cali8e70678eafb (disabled)
-- | --
ipv4_addresses | lo (127.0.0.1/8), enp3s0 (192.168.1.11/24), tunl0 (172.24.22.0/32), calib4abf8dfb89 (), cali4e5185ddf72 (), cali075bff664ca (), cali303eb7967f9 (), cali611775e31e0 (), calib9defee9036 (), calif3ddd7cfa65 (), cali739a2c3981e (), cali86a1a368924 (), cali949064e1ec0 (), cali943fe1d536d (), calicebae852fcf (), caliece5562bcb8 (), calidd74028fb16 (), calia4f62b51bd9 (), cali7e256393c2b (), cali012508cba3f (), calieec56e34117 (), cali09c8effd4ef (), caliabeed7346f8 (), cali7d80f4c964d (), calie0f6baf9f44 (), calibbd7aa3248a (), cali3eb1c02976f (), calid264146f5c7 (), caliea03d497ca9 (), calia828d864d01 (), cali41ae05f0d9c (), cali10d318aef30 (), cali1969a9deee6 (), calidd817121ae6 (), calie7974e17075 (), cali37ea9a823cf (), cali913315f6666 (), calid5f2082038a (), cali20dbd8049a5 (), cali8e70678eafb ()
ipv6_addresses | lo (::1/128), enp3s0 (fd0c:66af:42e0:2847:5a47:caff:fe77:95c2/64, fe80::5a47:caff:fe77:95c2/64), tunl0 (), calib4abf8dfb89 (fe80::ecee:eeff:feee:eeee/64), cali4e5185ddf72 (fe80::ecee:eeff:feee:eeee/64), cali075bff664ca (fe80::ecee:eeff:feee:eeee/64), cali303eb7967f9 (fe80::ecee:eeff:feee:eeee/64), cali611775e31e0 (fe80::ecee:eeff:feee:eeee/64), calib9defee9036 (fe80::ecee:eeff:feee:eeee/64), calif3ddd7cfa65 (fe80::ecee:eeff:feee:eeee/64), cali739a2c3981e (fe80::ecee:eeff:feee:eeee/64), cali86a1a368924 (fe80::ecee:eeff:feee:eeee/64), cali949064e1ec0 (fe80::ecee:eeff:feee:eeee/64), cali943fe1d536d (fe80::ecee:eeff:feee:eeee/64), calicebae852fcf (fe80::ecee:eeff:feee:eeee/64), caliece5562bcb8 (fe80::ecee:eeff:feee:eeee/64), calidd74028fb16 (fe80::ecee:eeff:feee:eeee/64), calia4f62b51bd9 (fe80::ecee:eeff:feee:eeee/64), cali7e256393c2b (fe80::ecee:eeff:feee:eeee/64), cali012508cba3f (fe80::ecee:eeff:feee:eeee/64), calieec56e34117 (fe80::ecee:eeff:feee:eeee/64), cali09c8effd4ef (fe80::ecee:eeff:feee:eeee/64), caliabeed7346f8 (fe80::ecee:eeff:feee:eeee/64), cali7d80f4c964d (fe80::ecee:eeff:feee:eeee/64), calie0f6baf9f44 (fe80::ecee:eeff:feee:eeee/64), calibbd7aa3248a (fe80::ecee:eeff:feee:eeee/64), cali3eb1c02976f (fe80::ecee:eeff:feee:eeee/64), calid264146f5c7 (fe80::ecee:eeff:feee:eeee/64), caliea03d497ca9 (fe80::ecee:eeff:feee:eeee/64), calia828d864d01 (fe80::ecee:eeff:feee:eeee/64), cali41ae05f0d9c (fe80::ecee:eeff:feee:eeee/64), cali10d318aef30 (fe80::ecee:eeff:feee:eeee/64), cali1969a9deee6 (fe80::ecee:eeff:feee:eeee/64), calidd817121ae6 (fe80::ecee:eeff:feee:eeee/64), calie7974e17075 (fe80::ecee:eeff:feee:eeee/64), cali37ea9a823cf (fe80::ecee:eeff:feee:eeee/64), cali913315f6666 (fe80::ecee:eeff:feee:eeee/64), calid5f2082038a (fe80::ecee:eeff:feee:eeee/64), cali20dbd8049a5 (fe80::ecee:eeff:feee:eeee/64), cali8e70678eafb (fe80::ecee:eeff:feee:eeee/64)
announce_addresses | 192.168.1.11, fd0c:66af:42e0:2847:5a47:caff:fe77:95c2, fe80::5a47:caff:fe77:95c2

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 26, 2025 at 2:51 PM
-- | --
current_recorder_run | July 30, 2025 at 10:46 PM
estimated_db_size | 6444.28 MiB
database_engine | mysql
database_version | 10.6.11

</details>

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/meshtastic/home-assistant/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The URLs to assets such as the SVGs of devices are broken because the URL requested is at the root (ex: "/t-deck.svg"). There might be other assets that also 404.

A simple workaround is to update the javascript for the static UI to add the missing path, here's a command to do so:

```bash
cat index-DdzfxeGq.js | sed 's/\/${i}/\/meshtastic\/web\/${i}/'
```

### Reproduction steps

1. Open Home Assistant and navigate to the Web UI for a device
2. Connect to the device in the web UI
3. Navigate to Nodes
4. Click on a node
5. Note that the stock image for the node in the top right is a broken image.

### Home Assistant Debug logs

```text
N/A
```

**Comment by KmanOz** [comment]
I see this as well

**Comment by broglep** [comment]
You can give the pre-release a try, it should already be resolved there: https://github.com/meshtastic/home-assistant/releases/tag/v0.6.2-rc1

**Comment by tyzbit** [comment]
That (`v0.6.2-rc1`) is the version I'm on, though I did redownload to that version from `v0.6.1` instead of a fresh install of the RC.

**Comment by KmanOz** [comment]
Upgraded to release 0.6.2. Still the same for me as well.

EDIT: Can also confirm the fix above works,

<img width="572" height="342" alt="Image" src="https://github.com/user-attachments/assets/7fe12914-581e-4e45-835c-4adfb6a0422c" />

**Comment by broglep** [comment]
It is [fixed](https://github.com/meshtastic/web/compare/main...broglep:meshtastic-web:homeassistant#diff-6e51e04185efe462b314db721dc080fefbcdd6fb19bcb30c0840c21fee98d3d6) and will be part of next release
